import type { DemoPatient } from "./domain";
import { createEpisode, createGenericTriage } from "./repository";

type PatientFixture = Omit<DemoPatient, "deterioration" | "episode" | "pain" | "triage"> & {
  pain?: number;
  triage?: DemoPatient["triage"];
};

const patientFixtures: PatientFixture[] = [
  {
    id: "DEMO-0001",
    name: "Demo Patient 01",
    age: 58,
    sex: "F",
    level: 2,
    status: "critical",
    waitMinutes: 0,
    bay: "R-1",
    arrivedAt: "2026-08-01T14:22:00-07:00",
    zone: "resuscitation",
    symptoms: ["chestPain", "dyspnea"],
    pain: 8,
    complaint: "critical",
    triage: {
      allergyCodes: ["penicillin"],
      medications: [{ code: "lisinopril", dose: "10 mg" }],
      onsetMinutes: 180,
      lastMeal: "08:30",
      vitals: [
        { code: "heartRate", value: "118", unit: "bpm", severity: "high" },
        { code: "bloodPressure", value: "156/98", unit: "mmHg", severity: "high" },
        { code: "respiratory", value: "24", unit: "breathsPerMinute", severity: "medium" },
        { code: "oxygen", value: "93", unit: "percent", severity: "medium" },
        { code: "temperature", value: "37.2", unit: "celsius", severity: "low" },
        { code: "gcs", value: "15", unit: "gcs", severity: "low" },
      ],
      vitalsObservedAt: "2026-08-01T14:38:00-07:00",
      visitDates: ["2025-03-12", "2024-11-04", "2024-08-21"],
      factorCodes: [
        "radiatingChestPain",
        "heartRateAbove110",
        "oxygenBelow94",
        "ageAbove50",
        "hypertension",
      ],
      narrativeCode: "cardiorespiratory",
    },
    isSynthetic: true,
  },
  {
    id: "DEMO-0002",
    name: "Demo Patient 02",
    age: 71,
    sex: "M",
    level: 1,
    status: "critical",
    waitMinutes: 0,
    bay: "R-2",
    arrivedAt: "2026-08-01T14:18:00-07:00",
    zone: "resuscitation",
    symptoms: ["dizziness"],
    complaint: "critical",
    isSynthetic: true,
  },
  {
    id: "DEMO-0003",
    name: "Demo Patient 03",
    age: 34,
    sex: "F",
    level: 2,
    status: "treatment",
    waitMinutes: 8,
    bay: "T-4",
    arrivedAt: "2026-08-01T14:05:00-07:00",
    zone: "trauma",
    symptoms: ["abdominalPain"],
    complaint: "treatment",
    isSynthetic: true,
  },
  {
    id: "DEMO-0004",
    name: "Demo Patient 04",
    age: 22,
    sex: "M",
    level: 3,
    status: "imaging",
    waitMinutes: 14,
    bay: "T-7",
    arrivedAt: "2026-08-01T13:58:00-07:00",
    zone: "trauma",
    symptoms: ["bleeding"],
    complaint: "imaging",
    isSynthetic: true,
  },
  {
    id: "DEMO-0005",
    name: "Demo Patient 05",
    age: 67,
    sex: "F",
    level: 2,
    status: "treatment",
    waitMinutes: 5,
    bay: "T-2",
    arrivedAt: "2026-08-01T13:55:00-07:00",
    zone: "trauma",
    symptoms: ["dyspnea"],
    complaint: "treatment",
    isSynthetic: true,
  },
  {
    id: "DEMO-0006",
    name: "Demo Patient 06",
    age: 45,
    sex: "M",
    level: 4,
    status: "waiting",
    waitMinutes: 32,
    bay: null,
    arrivedAt: "2026-08-01T13:48:00-07:00",
    zone: "trauma",
    symptoms: ["fever"],
    complaint: "waiting",
    isSynthetic: true,
  },
  {
    id: "DEMO-0007",
    name: "Demo Patient 07",
    age: 9,
    sex: "F",
    level: 3,
    status: "treatment",
    waitMinutes: 2,
    bay: "P-1",
    arrivedAt: "2026-08-01T13:42:00-07:00",
    zone: "pediatrics",
    symptoms: ["dyspnea"],
    complaint: "pediatric",
    isSynthetic: true,
  },
  {
    id: "DEMO-0008",
    name: "Demo Patient 08",
    age: 60,
    sex: "M",
    level: 4,
    status: "waiting",
    waitMinutes: 41,
    bay: null,
    arrivedAt: "2026-08-01T13:30:00-07:00",
    zone: "trauma",
    symptoms: ["headache"],
    complaint: "waiting",
    isSynthetic: true,
  },
  {
    id: "DEMO-0009",
    name: "Demo Patient 09",
    age: 28,
    sex: "F",
    level: 5,
    status: "waiting",
    waitMinutes: 58,
    bay: null,
    arrivedAt: "2026-08-01T13:18:00-07:00",
    zone: "pediatrics",
    symptoms: ["headache"],
    complaint: "waiting",
    isSynthetic: true,
  },
  {
    id: "DEMO-0010",
    name: "Demo Patient 10",
    age: 51,
    sex: "M",
    level: 5,
    status: "discharging",
    waitMinutes: null,
    bay: "T-9",
    arrivedAt: "2026-08-01T12:55:00-07:00",
    zone: "trauma",
    symptoms: [],
    complaint: "discharge",
    isSynthetic: true,
  },
];

export const initialPatients: DemoPatient[] = patientFixtures.map((patient) => ({
  ...patient,
  deterioration: patient.status === "critical" ? "active" : patient.level <= 2 ? "watch" : "none",
  pain: patient.pain ?? 0,
  triage: patient.triage ?? createGenericTriage(),
  episode: createEpisode(
    patient.id,
    patient.arrivedAt,
    patient.status === "critical" ? "critical" : null,
  ),
}));
