/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ErRouteImport } from './routes/er'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as TriagePatientIdRouteImport } from './routes/triage_.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ErRoute = ErRouteImport.update({
  id: '/er',
  path: '/er',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const TriagePatientIdRoute = TriagePatientIdRouteImport.update({
  id: '/triage_/$patientId',
  path: '/triage/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/er': typeof ErRoute
  '/kiosk': typeof KioskRoute
  '/triage': typeof TriageRoute
  '/triage/$patientId': typeof TriagePatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/er': typeof ErRoute
  '/kiosk': typeof KioskRoute
  '/triage': typeof TriageRoute
  '/triage/$patientId': typeof TriagePatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/er': typeof ErRoute
  '/kiosk': typeof KioskRoute
  '/triage': typeof TriageRoute
  '/triage_/$patientId': typeof TriagePatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin' | '/er' | '/kiosk' | '/triage' | '/triage/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/er' | '/kiosk' | '/triage' | '/triage/$patientId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/er'
    | '/kiosk'
    | '/triage'
    | '/triage_/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ErRoute: typeof ErRoute
  KioskRoute: typeof KioskRoute
  TriageRoute: typeof TriageRoute
  TriagePatientIdRoute: typeof TriagePatientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/er': {
      id: '/er'
      path: '/er'
      fullPath: '/er'
      preLoaderRoute: typeof ErRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triage_/$patientId': {
      id: '/triage_/$patientId'
      path: '/triage/$patientId'
      fullPath: '/triage/$patientId'
      preLoaderRoute: typeof TriagePatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ErRoute: ErRoute,
  KioskRoute: KioskRoute,
  TriageRoute: TriageRoute,
  TriagePatientIdRoute: TriagePatientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
